[package]
name = "actix_web_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["macros", "full"] }
tower = "0.4.13"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
